#!/bin/sh
if [[ $* == *-e* ]] || [[ $* == *--evaluate* ]]; then
  # exits with the number in the results file
  exit $(cat $2);
elif [[ $* == *-s* ]] || [[ $* == *--start* ]]; then
  # entry point for docker test container
  echo $PATH;
  git --version;
  mkdir -p ../results;
  rm -rf ../results/*.test
  cd ./tests/scripts;
  ls | xargs -I{} ../../test --run {};
elif [[ $* == *-r* ]] || [[ $* == *--run* ]]; then
  # run script and print exit code to ./tests/results/<filename>
  chmod +x $(dirname $0)/tests/scripts/$2;
  printf "__________________________________________________________________________\n";
  printf "TEST MODULE  : $2\n";
  printf "CURRENT DIR  : $(pwd)\n"
  printf "CURRENT PATH : ${PATH}\n"
  printf "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n";
  sh $(dirname $0)/tests/scripts/$2;
  pwd
  ls -lA
  echo $(dirname $0);
  echo $(dirname $0)/tests/results/$2;
  ls -lA $(dirname $0);
  ls -lA $(dirname $0)/tests
  printf "$?" > $(dirname $0)/tests/results/$2;
else
  # run test container and evaluate results after
  docker-compose -f ./tests/docker-compose.yml up --build;
  ls tests/results | xargs -n 1 -I@ sh -c "$(dirname $0)/test --evaluate tests/results/@";
fi;
